base_config: har_experiment.yaml

runtime:
  cuda_visible_devices: "3"

experiment:
  variant_name: full_linear
  tags: ["skeleton-gircse", "full_linear"]

text_branch:
  description_variant: full

model:
  projector:
    type: linear

train_presets:
  skeleton_gircse:
    train:
      batch_size: 4
      gradient_accumulation_steps: 8
