base_config: har_experiment.yaml

experiment:
  variant_name: label_general
  tags: ["skeleton-gircse", "label_general"]

text_branch:
  description_variant: label_only

model:
  projector:
    type: general_qformer
