base_config: har_experiment.yaml

experiment:
  variant_name: full_general
  tags: ["skeleton-gircse", "full_general"]

text_branch:
  description_variant: full

model:
  projector:
    type: general_qformer
