base_config: /data/chenle/GIRCSE/HAR/configs/ntu60_zsl.yaml

experiment:
  tags: ["ntu60", "zsl", "48-12", "synse-purls"]

paths:
  shift_gcn_seen_checkpoint: /data/chenle/GIRCSE/HAR/outputs/models/shift_gcn_seen_ntu60_48_12.ckpt

dataset:
  split_protocol: synse_purls
  split_name: "48_12"
  seen_classes: [0, 1, 2, 4, 6, 7, 8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 43, 44, 45, 46, 48, 49, 50, 52, 53, 54, 55, 57]
  unseen_classes: [3, 5, 9, 12, 15, 40, 42, 47, 51, 56, 58, 59]
