base_config: /data/chenle/GIRCSE/HAR/configs/ntu120_zsl_110_10.yaml

experiment:
  tags: ["ntu120", "110-10", "projector-linear"]

model:
  projector:
    type: linear
    in_dim: 256
    llm_dim: 4096
    target_temporal_bins: 4
