base_config: /data/chenle/GIRCSE/HAR/configs/ntu120_zsl_110_10.yaml

experiment:
  tags: ["ntu120", "110-10", "warmup", "classwise-infonce"]

train:
  stage: prealign
  epochs: 10
  batch_size: 16
  lr_projector: 0.0001
  lr_shift_gcn: 0.00001
  freeze_shift_gcn: true
  eval_during_train: false

loss:
  type: classwise_infonce
  temperature: 0.05

model:
  shift_gcn:
    pretrained_path: /data/chenle/GIRCSE/HAR/outputs/models/shift_gcn_seen_ntu120_110_10.ckpt
